GET http://localhost:4000/spire

###



GET http://localhost:4000/spire/5f88101836ab0c1e58d0c74c

###

POST http://localhost:4000/spire/add
Content-Type: application/json

{
    "firstName": "7777r",
    "lastName": "alsalemi",
    "coures": "Java",
    "emailAddress": "alsaemi1987@gmail.com",
    "phoneNumber": "862-263-4504",
    "address": "13765 56th ave S",
    "city": "tukwila"

}
###
DELETE http://localhost:4000/spire/5f8bdc178d8b5430345fa978
###
PATCH  http://localhost:4000/spire/5f9ae4fe0e189361247eabfe
Content-Type: application/json

{
    "firstName": "newname"
}

 